home:
  route: "/"
  controller: "controllers/HomeController.php"

login:
  route: "/login"
  controller: "controllers/LoginController.php"

register:
  route: "/register"
  controller: "controllers/RegisterController.php"

admin:
  route: "/admin"
  controller: "controllers/AdminController.php"

user:
  route: "/perfil"
  controller: "controllers/UserProfileController.php"

tasks:
  route: "/tareas"
  controller: "controllers/TasksController.php"